task-16. Can one block of except statements handle multiple exception?

Ans.  Yes, a single block of except statements in Python can handle multiple exceptions. This feature allows you to handle different types of exceptions using a single block of code.